FROM ubuntu:focal
MAINTAINER Steven Velozo <steven@velozo.com>

# Prepare APT
ENV DEBIAN_FRONTEND noninteractive
# Install node.js
RUN apt update && apt install -y curl git sudo wkhtmltopdf && curl --silent --location https://deb.nodesource.com/setup_12.x | sudo bash - && apt install --yes nodejs && rm -rf /var/lib/apt/lists/*

ADD . /tidings
WORKDIR /tidings
RUN npm install
RUN ./InitializeOptionalUbuntuSoftware.sh
RUN ./InitializeOptionalModules.sh
RUN mkdir stage

# Clean APT
RUN rm -rf /var/lib/apt/lists/*

#Web server port
EXPOSE 8080

CMD ["node", "examples/Debug.js"]
